use crate::models::{Category, Equipment, Exercise, ExerciseTrackingType};

fn ex(
    id: &str,
    name: &str,
    cat: Category,
    equip: Equipment,
    muscles: &[&str],
    desc: &str,
) -> Exercise {
    ex_t(
        id,
        name,
        cat,
        equip,
        muscles,
        desc,
        ExerciseTrackingType::Strength,
    )
}

fn ex_t(
    id: &str,
    name: &str,
    cat: Category,
    equip: Equipment,
    muscles: &[&str],
    desc: &str,
    tt: ExerciseTrackingType,
) -> Exercise {
    // Default to .svg, but allowing contributors to easily change extensions here
    let image_path = format!("icons/exercises/{}.svg", id);
    Exercise {
        id: id.to_string(),
        name: name.to_string(),
        category: cat,
        equipment: equip,
        muscle_groups: muscles.iter().map(|s| s.to_string()).collect(),
        description: desc.to_string(),
        is_custom: false,
        image: Some(image_path),
        tracking_type: tt,
    }
}

pub fn default_exercises() -> Vec<Exercise> {
    vec![
        // === CHEST ===
        ex("chest-01", "Barbell Bench Press", Category::Chest, Equipment::Barbell,
           &["Chest", "Triceps", "Front Delts"],
           "Lie on bench, grip bar slightly wider than shoulders. Lower to chest, press up to lockout."),
        ex("chest-02", "Incline Barbell Bench Press", Category::Chest, Equipment::Barbell,
           &["Upper Chest", "Triceps", "Front Delts"],
           "Set bench to 30-45 degrees. Lower bar to upper chest, press up."),
        ex("chest-03", "Decline Barbell Bench Press", Category::Chest, Equipment::Barbell,
           &["Lower Chest", "Triceps"],
           "Set bench to decline. Lower bar to lower chest, press up."),
        ex("chest-04", "Dumbbell Bench Press", Category::Chest, Equipment::Dumbbell,
           &["Chest", "Triceps", "Front Delts"],
           "Lie on bench with dumbbells. Press up, lower with control."),
        ex("chest-05", "Incline Dumbbell Press", Category::Chest, Equipment::Dumbbell,
           &["Upper Chest", "Triceps", "Front Delts"],
           "Incline bench at 30-45 degrees. Press dumbbells up from shoulders."),
        ex("chest-06", "Dumbbell Fly", Category::Chest, Equipment::Dumbbell,
           &["Chest"],
           "Lie on bench, arms extended with slight bend. Lower dumbbells in arc, squeeze back up."),
        ex("chest-07", "Cable Fly", Category::Chest, Equipment::Cable,
           &["Chest"],
           "Stand between cable stations. Bring handles together in front of chest with slight elbow bend."),
        ex("chest-08", "Pec Deck Machine", Category::Chest, Equipment::Machine,
           &["Chest"],
           "Setup: Adjust seat height so handles align with mid-chest. Set the arm pads or handles so your arms start at about 70-80 degrees out to your sides — you should feel a mild stretch but no shoulder strain. Sit with back flat against pad, feet flat on floor. Execution: Place forearms against pads (or grip handles). Bring arms together in front of chest in a hugging motion. Squeeze chest hard at the center, then return slowly to start. Keep a slight bend in elbows throughout. Avoid letting the weight stack slam at the bottom."),
        ex("chest-09", "Machine Chest Press", Category::Chest, Equipment::Machine,
           &["Chest", "Triceps", "Front Delts"],
           "Setup: Adjust seat height so the handles line up with your mid-to-lower chest (nipple line). Your feet should be flat on the floor. Sit with back firmly against the pad and grip the handles. Some machines have a foot lever to bring the handles into starting position — use it to avoid straining your shoulders. Execution: Press handles forward until arms are nearly straight but not locked out. Return slowly until you feel a stretch across the chest. Keep shoulder blades pinched back against the pad throughout. Don't arch your lower back off the seat."),
        ex_t("chest-10", "Push-ups", Category::Chest, Equipment::Bodyweight,
           &["Chest", "Triceps", "Front Delts", "Core"],
           "Hands shoulder-width apart, body straight. Lower chest to ground, push back up.",
           ExerciseTrackingType::Bodyweight),
        ex_t("chest-11", "Dips (Chest)", Category::Chest, Equipment::Bodyweight,
           &["Lower Chest", "Triceps", "Front Delts"],
           "Lean forward on parallel bars. Lower body until upper arms are parallel, press up.",
           ExerciseTrackingType::Bodyweight),
        ex("chest-12", "Cable Crossover", Category::Chest, Equipment::Cable,
           &["Chest"],
           "Set cables high. Step forward, bring handles down and together in arc."),
        ex("chest-13", "Smith Machine Bench Press", Category::Chest, Equipment::Machine,
           &["Chest", "Triceps", "Front Delts"],
           "Lie on bench under Smith machine bar. Unrack, lower to chest, press up to lockout."),

        // === BACK ===
        ex("back-01", "Lat Pulldown", Category::Back, Equipment::Cable,
           &["Lats", "Biceps", "Rear Delts"],
           "Setup: Attach a wide bar to the high cable. Adjust the thigh pad so it sits snugly on your thighs when seated — this keeps you from lifting off the seat during heavy pulls. Sit down and grip the bar wider than shoulder-width with an overhand grip. Execution: Pull the bar down to your upper chest, driving your elbows down and back. Squeeze your lats at the bottom, then return the bar up with control until your arms are fully extended and you feel a stretch in your lats. Keep your torso upright or with only a very slight lean back. Avoid pulling behind the neck — always pull to the front."),
        ex("back-02", "Seated Cable Row", Category::Back, Equipment::Cable,
           &["Mid Back", "Lats", "Biceps", "Rear Delts"],
           "Setup: Attach a V-handle or close-grip handle to the low cable. Sit on the bench with feet on the foot platform, knees slightly bent. Reach forward to grab the handle. Start with arms extended, slight forward lean, back straight. Execution: Pull the handle to your lower chest/upper abdomen, driving elbows back past your torso. Squeeze your shoulder blades together at full contraction. Return with control, letting your arms extend and shoulders stretch forward slightly. Keep your lower back neutral — don't round or excessively arch. The torso should stay mostly upright; a small amount of controlled lean is acceptable."),
        ex("back-03", "Barbell Bent-over Row", Category::Back, Equipment::Barbell,
           &["Mid Back", "Lats", "Biceps", "Rear Delts"],
           "Hinge at hips, back flat. Pull barbell to lower chest, squeeze back."),
        ex("back-04", "Dumbbell Row", Category::Back, Equipment::Dumbbell,
           &["Lats", "Mid Back", "Biceps"],
           "One hand on bench, row dumbbell to hip. Keep elbow close to body."),
        ex("back-05", "Deadlift", Category::Back, Equipment::Barbell,
           &["Lower Back", "Glutes", "Hamstrings", "Traps"],
           "Stand over bar, hip-width grip. Drive through heels, extend hips and knees together."),
        ex("back-06", "Romanian Deadlift", Category::Back, Equipment::Barbell,
           &["Hamstrings", "Lower Back", "Glutes"],
           "Hold bar at hips. Hinge forward keeping legs nearly straight, lower to mid-shin."),
        ex_t("back-07", "Pull-ups", Category::Back, Equipment::Bodyweight,
           &["Lats", "Biceps", "Rear Delts"],
           "Grip bar overhand wider than shoulders. Pull chin over bar, lower with control.",
           ExerciseTrackingType::Bodyweight),
        ex_t("back-08", "Chin-ups", Category::Back, Equipment::Bodyweight,
           &["Lats", "Biceps"],
           "Grip bar underhand shoulder-width. Pull chin over bar, lower with control.",
           ExerciseTrackingType::Bodyweight),
        ex("back-09", "T-Bar Row", Category::Back, Equipment::Barbell,
           &["Mid Back", "Lats", "Biceps"],
           "Straddle T-bar, grip handle. Pull to chest, squeeze back, lower with control."),
        ex("back-10", "Cable Pullover", Category::Back, Equipment::Cable,
           &["Lats"],
           "Face cable machine, grip bar overhead. Pull down in arc to thighs, keeping arms straight."),
        ex("back-11", "Machine Row", Category::Back, Equipment::Machine,
           &["Mid Back", "Lats", "Biceps"],
           "Setup: Adjust the chest pad so you can fully extend your arms and just barely reach the handles. Adjust seat height so the handles are at lower chest or upper abdomen level. Sit with chest firmly pressed into the pad, feet flat on the floor or on the foot platform. Execution: Pull handles toward your torso, driving elbows back. Squeeze shoulder blades together at the end of the pull — hold for a beat. Return with control, letting your arms fully extend to stretch the lats. Keep chest against the pad throughout; don't lean back to cheat the weight."),
        ex_t("back-12", "Hyperextension", Category::Back, Equipment::Bodyweight,
           &["Lower Back", "Glutes", "Hamstrings"],
           "Lock feet in hyperextension bench. Lower torso, extend back to straight position.",
           ExerciseTrackingType::Bodyweight),

        // === LEGS ===
        ex("legs-01", "Barbell Squat", Category::Legs, Equipment::Barbell,
           &["Quads", "Glutes", "Hamstrings", "Core"],
           "Bar on upper back, feet shoulder-width. Squat to parallel or below, drive up."),
        ex("legs-02", "Front Squat", Category::Legs, Equipment::Barbell,
           &["Quads", "Glutes", "Core"],
           "Bar on front delts, elbows high. Squat keeping torso upright, drive up."),
        ex("legs-03", "Leg Press", Category::Legs, Equipment::Machine,
           &["Quads", "Glutes", "Hamstrings"],
           "Setup: Sit in the sled with your back and hips flat against the pad. Place feet shoulder-width on the platform — higher foot placement targets glutes/hamstrings more, lower placement targets quads more. Adjust the safety catches so you can reach full depth without rounding your lower back. Unlock the sled by turning the side handles. Execution: Lower the sled by bending your knees toward your chest until you reach about 90 degrees. Press through your whole foot back to the starting position. Don't lock knees at the top. Keep your lower back pressed into the seat throughout — if your hips curl up at the bottom, you're going too deep."),
        ex("legs-04", "Leg Extension", Category::Legs, Equipment::Machine,
           &["Quads"],
           "Setup: Adjust the backrest so your knees align with the machine's pivot point (usually marked with a dot or line on the side). Adjust the shin pad so it sits just above your ankles on the front of your lower legs. Set the starting position so your knees are at about 90 degrees. Sit with back against pad, grip the side handles. Execution: Extend your legs until they're straight, squeezing your quads hard at the top. Hold for a beat, then lower with control — don't let the weight drop. Avoid swinging or using momentum. For knee safety, don't go excessively heavy; focus on controlled reps."),
        ex("legs-05", "Leg Curl (Lying)", Category::Legs, Equipment::Machine,
           &["Hamstrings"],
           "Setup: Lie face down on the bench. Adjust the leg pad so it sits just above your ankles on the back of your lower legs. Your knees should be just off the edge of the bench and aligned with the machine's pivot point. Grip the handles under the bench. Execution: Curl your heels toward your glutes, squeezing hamstrings at the top. Lower with a slow, controlled tempo — don't let the weight slam down. Keep your hips pressed against the bench; if they rise, the weight is too heavy. Point your toes slightly away from you to better engage the hamstrings."),
        ex("legs-06", "Leg Curl (Seated)", Category::Legs, Equipment::Machine,
           &["Hamstrings"],
           "Setup: Adjust the backrest so your knees align with the machine's pivot point. Set the upper thigh pad snug against your thighs just above the knees — it should hold you down but not be uncomfortably tight. Adjust the lower leg pad to sit just above your ankles on the back of your legs. Start with legs extended. Execution: Curl your legs down and back, pulling heels under the seat. Squeeze hamstrings at full contraction, then return with control to the start. Keep your back against the pad throughout and avoid jerking the weight."),
        ex("legs-07", "Hack Squat", Category::Legs, Equipment::Machine,
           &["Quads", "Glutes"],
           "Setup: Step onto the platform and place your back against the sliding pad. Position shoulders under the shoulder pads. Place feet shoulder-width on the platform — foot position affects targeting just like the leg press. Release the safety handles on the sides. Execution: Lower your body by bending knees to about 90 degrees (or deeper if comfortable). Drive through your feet to push back up. Keep your back flat against the pad at all times. Don't lock knees at the top. Re-engage the safety handles when finished."),
        ex("legs-08", "Bulgarian Split Squat", Category::Legs, Equipment::Dumbbell,
           &["Quads", "Glutes", "Hamstrings"],
           "Rear foot on bench, front foot forward. Lower until front thigh is parallel, drive up."),
        ex("legs-09", "Walking Lunges", Category::Legs, Equipment::Dumbbell,
           &["Quads", "Glutes", "Hamstrings"],
           "Step forward into lunge, knee to 90 degrees. Push off front foot, step into next lunge."),
        ex("legs-10", "Calf Raise (Standing)", Category::Legs, Equipment::Machine,
           &["Calves"],
           "Setup: Step under the shoulder pads and stand on the edge of the foot platform with the balls of your feet. Your heels should hang off the edge. Adjust the shoulder pad height so you're standing straight with a slight knee bend. Execution: Rise up onto your toes as high as possible, squeezing your calves at the top. Hold for a beat, then lower your heels below the platform level for a deep stretch. Keep the movement slow and controlled — avoid bouncing. Keep knees slightly bent and body upright throughout."),
        ex("legs-11", "Calf Raise (Seated)", Category::Legs, Equipment::Machine,
           &["Calves"],
           "Setup: Sit on the machine and place the balls of your feet on the foot platform with heels hanging off. Adjust the knee pad so it sits snugly on your lower thighs just above the knees — tight enough to hold you down but not painful. Release the safety bar. Execution: Press up through your toes as high as possible, squeezing calves at the top. Lower your heels slowly below the platform for a full stretch. The seated position primarily targets the soleus (deeper calf muscle) while standing targets the gastrocnemius (outer calf)."),
        ex("legs-12", "Goblet Squat", Category::Legs, Equipment::Dumbbell,
           &["Quads", "Glutes", "Core"],
           "Hold dumbbell at chest. Squat deep keeping torso upright, drive up."),
        ex("legs-13", "Hip Thrust", Category::Legs, Equipment::Barbell,
           &["Glutes", "Hamstrings"],
           "Upper back on bench, bar over hips. Drive hips up to full extension, squeeze glutes."),
        ex("legs-14", "Leg Press Calf Raise", Category::Legs, Equipment::Machine,
           &["Calves"],
           "Setup: Sit in the leg press with back and hips flat against the pad. Place only the balls of your feet and toes on the very bottom edge of the foot platform — heels should be off the platform entirely. Use a lighter weight than your normal leg press. Unlock the sled and press to a nearly straight leg position (this is your starting position). Execution: Push through your toes to extend your ankles, then slowly allow your toes to come back toward you for a stretch. Keep the sled locked out at the knees — all movement is at the ankle joint. Keep safety catches engaged close by."),
        ex("legs-15", "Smith Machine Squat", Category::Legs, Equipment::Machine,
           &["Quads", "Glutes"],
           "Setup: Set the bar at upper chest height on the Smith machine. Step under the bar and position it across your upper traps (not your neck). Place feet shoulder-width apart, slightly in front of the bar — this is different from free squats because the bar path is fixed. Twist the bar to unhook it from the safety catches. Set the safety stops at a height just below your lowest squat depth. Execution: Squat down by bending knees and hips until thighs are at least parallel. Drive up through your feet. The fixed bar path means you can lean back slightly and emphasize quads. Re-rack by twisting the bar back into the hooks."),
        ex("legs-16", "Hip Abductor", Category::Legs, Equipment::Machine,
           &["Glutes", "Hip Abductors"],
           "Sit with pads on outer thighs. Push legs apart against resistance, return with control."),
        ex("legs-17", "Hip Adductor", Category::Legs, Equipment::Machine,
           &["Inner Thighs", "Hip Adductors"],
           "Sit with pads on inner thighs. Squeeze legs together against resistance, return with control."),

        // === SHOULDERS ===
        ex("shldr-01", "Overhead Press (Barbell)", Category::Shoulders, Equipment::Barbell,
           &["Front Delts", "Side Delts", "Triceps"],
           "Bar at shoulder height. Press overhead to lockout, lower to shoulders."),
        ex("shldr-02", "Dumbbell Shoulder Press", Category::Shoulders, Equipment::Dumbbell,
           &["Front Delts", "Side Delts", "Triceps"],
           "Dumbbells at shoulders. Press overhead, lower with control."),
        ex("shldr-03", "Lateral Raise", Category::Shoulders, Equipment::Dumbbell,
           &["Side Delts"],
           "Dumbbells at sides. Raise arms out to sides until parallel to ground, lower with control."),
        ex("shldr-04", "Front Raise", Category::Shoulders, Equipment::Dumbbell,
           &["Front Delts"],
           "Dumbbells in front of thighs. Raise one or both arms to shoulder height, lower."),
        ex("shldr-05", "Face Pull", Category::Shoulders, Equipment::Cable,
           &["Rear Delts", "Traps", "Rotator Cuff"],
           "Cable at face height with rope. Pull to face, externally rotate, squeeze rear delts."),
        ex("shldr-06", "Rear Delt Fly (Dumbbell)", Category::Shoulders, Equipment::Dumbbell,
           &["Rear Delts"],
           "Bend forward, dumbbells hanging. Raise arms out to sides, squeeze rear delts."),
        ex("shldr-07", "Machine Shoulder Press", Category::Shoulders, Equipment::Machine,
           &["Front Delts", "Side Delts", "Triceps"],
           "Setup: Adjust the seat height so the handles start at about ear level when seated. Your upper arms should be roughly parallel to the ground in the starting position. Sit with back firmly against the pad and feet flat on the floor. Grip the handles — most machines offer both a wide and narrow grip; the wider grip emphasizes side delts more. Execution: Press the handles overhead until arms are nearly straight but not locked out. Lower with control back to the starting position. Keep your back against the pad; don't arch excessively. Keep your core braced throughout."),
        ex("shldr-08", "Cable Lateral Raise", Category::Shoulders, Equipment::Cable,
           &["Side Delts"],
           "Stand next to low cable. Raise arm out to side to shoulder height."),
        ex("shldr-09", "Arnold Press", Category::Shoulders, Equipment::Dumbbell,
           &["Front Delts", "Side Delts", "Triceps"],
           "Start with palms facing you at shoulders. Rotate and press overhead."),
        ex("shldr-10", "Upright Row", Category::Shoulders, Equipment::Barbell,
           &["Side Delts", "Traps"],
           "Grip bar narrow. Pull up along body to chin height, elbows leading."),
        ex("shldr-11", "Reverse Pec Deck", Category::Shoulders, Equipment::Machine,
           &["Rear Delts"],
           "Setup: This uses the same machine as the Pec Deck but facing the opposite direction. Adjust the seat so the handles are at shoulder height when seated. Sit facing the pad with your chest against it. Grip the handles with a neutral or overhand grip — arms should be extended in front of you. Some machines have specific rear delt handles; use those if available. Execution: Push the handles back and out in a reverse fly motion, squeezing your rear delts and upper back at full contraction. Return slowly to start. Keep a slight bend in the elbows throughout. Don't lean back or use momentum."),
        ex("shldr-12", "Shrugs (Barbell)", Category::Shoulders, Equipment::Barbell,
           &["Traps"],
           "Hold barbell at thighs. Shrug shoulders up toward ears, hold, lower."),
        ex("shldr-13", "Shrugs (Dumbbell)", Category::Shoulders, Equipment::Dumbbell,
           &["Traps"],
           "Hold dumbbells at sides. Shrug shoulders up toward ears, hold, lower."),

        // === ARMS ===
        ex("arms-01", "Barbell Curl", Category::Arms, Equipment::Barbell,
           &["Biceps"],
           "Stand with barbell, underhand grip. Curl to shoulders keeping elbows fixed, lower."),
        ex("arms-02", "Dumbbell Curl", Category::Arms, Equipment::Dumbbell,
           &["Biceps"],
           "Stand with dumbbells. Curl to shoulders, lower with control. Alternate or together."),
        ex("arms-03", "Hammer Curl", Category::Arms, Equipment::Dumbbell,
           &["Biceps", "Brachialis", "Forearms"],
           "Hold dumbbells with neutral grip. Curl up keeping palms facing each other, lower."),
        ex("arms-04", "Preacher Curl", Category::Arms, Equipment::Barbell,
           &["Biceps"],
           "Arms on preacher bench pad. Curl bar up, lower with full extension."),
        ex("arms-05", "Cable Curl", Category::Arms, Equipment::Cable,
           &["Biceps"],
           "Face low cable with bar attachment. Curl up, squeeze biceps, lower with control."),
        ex("arms-06", "Concentration Curl", Category::Arms, Equipment::Dumbbell,
           &["Biceps"],
           "Sit, elbow on inner thigh. Curl dumbbell to shoulder, squeeze, lower."),
        ex("arms-07", "Tricep Pushdown", Category::Arms, Equipment::Cable,
           &["Triceps"],
           "Face high cable with bar/rope. Push down to full extension, return with control."),
        ex("arms-08", "Overhead Tricep Extension", Category::Arms, Equipment::Dumbbell,
           &["Triceps"],
           "Hold dumbbell overhead with both hands. Lower behind head, extend back up."),
        ex("arms-09", "Skull Crushers", Category::Arms, Equipment::Barbell,
           &["Triceps"],
           "Lie on bench, bar overhead. Lower to forehead bending elbows, extend back up."),
        ex_t("arms-10", "Tricep Dips", Category::Arms, Equipment::Bodyweight,
           &["Triceps", "Chest", "Front Delts"],
           "On parallel bars, body upright. Lower body bending elbows, press back up.",
           ExerciseTrackingType::Bodyweight),
        ex("arms-11", "Cable Overhead Extension", Category::Arms, Equipment::Cable,
           &["Triceps"],
           "Face away from low cable with rope. Extend arms overhead, squeeze triceps."),
        ex("arms-12", "Close-Grip Bench Press", Category::Arms, Equipment::Barbell,
           &["Triceps", "Chest"],
           "Lie on bench, narrow grip on bar. Lower to chest, press up focusing on triceps."),
        ex("arms-13", "Wrist Curl", Category::Arms, Equipment::Dumbbell,
           &["Forearms"],
           "Sit with forearms on thighs, palms up. Curl wrists up, lower with control."),
        ex("arms-14", "Reverse Curl", Category::Arms, Equipment::Barbell,
           &["Forearms", "Biceps"],
           "Stand with barbell, overhand grip. Curl up keeping overhand grip, lower."),

        // === CORE ===
        ex_t("core-01", "Plank", Category::Core, Equipment::Bodyweight,
           &["Core", "Abs", "Lower Back"],
           "Forearms and toes on ground, body straight. Hold position, keep core tight.",
           ExerciseTrackingType::Duration),
        ex_t("core-02", "Crunches", Category::Core, Equipment::Bodyweight,
           &["Abs"],
           "Lie on back, knees bent. Curl shoulders off ground, squeeze abs, lower.",
           ExerciseTrackingType::Bodyweight),
        ex_t("core-03", "Hanging Leg Raise", Category::Core, Equipment::Bodyweight,
           &["Lower Abs", "Hip Flexors"],
           "Hang from bar. Raise legs to parallel or higher, lower with control.",
           ExerciseTrackingType::Bodyweight),
        ex("core-04", "Cable Crunch", Category::Core, Equipment::Cable,
           &["Abs"],
           "Kneel at cable machine with rope at head. Crunch down, squeeze abs, return."),
        ex_t("core-05", "Russian Twist", Category::Core, Equipment::Bodyweight,
           &["Obliques", "Abs"],
           "Sit with feet off ground, lean back slightly. Rotate torso side to side.",
           ExerciseTrackingType::Bodyweight),
        ex("core-06", "Ab Wheel Rollout", Category::Core, Equipment::Other,
           &["Abs", "Core"],
           "Kneel with ab wheel. Roll forward extending body, pull back using abs."),
        ex_t("core-07", "Mountain Climbers", Category::Core, Equipment::Bodyweight,
           &["Core", "Hip Flexors", "Cardio"],
           "Push-up position. Alternate driving knees to chest rapidly.",
           ExerciseTrackingType::Bodyweight),
        ex_t("core-08", "Side Plank", Category::Core, Equipment::Bodyweight,
           &["Obliques", "Core"],
           "Lie on side, forearm on ground. Lift hips, body straight. Hold position.",
           ExerciseTrackingType::Duration),
        ex_t("core-09", "Bicycle Crunch", Category::Core, Equipment::Bodyweight,
           &["Abs", "Obliques"],
           "Lie on back, hands behind head. Alternate elbow to opposite knee in pedaling motion.",
           ExerciseTrackingType::Bodyweight),
        ex_t("core-10", "Dead Bug", Category::Core, Equipment::Bodyweight,
           &["Core", "Abs"],
           "Lie on back, arms up, knees at 90. Extend opposite arm and leg, return, alternate.",
           ExerciseTrackingType::Bodyweight),
        ex_t("core-11", "Decline Sit-up", Category::Core, Equipment::Bodyweight,
           &["Abs", "Hip Flexors"],
           "Lie on decline bench, feet hooked. Sit up fully, lower with control.",
           ExerciseTrackingType::Bodyweight),

        // === CARDIO ===
        ex_t("cardio-01", "Treadmill", Category::Cardio, Equipment::Machine,
           &["Cardio", "Legs"],
           "Setup: Step onto the side rails (not the belt) and attach the safety clip to your clothing — this stops the belt if you fall. Start the machine at a low speed (2-3 km/h) and step onto the belt. Adjust speed gradually. Set incline using the incline buttons (0-15% on most machines). Controls: Speed buttons adjust pace, incline buttons adjust slope. Most machines have preset programs and a heart rate monitor on the handles. Execution: Walk, jog, or run at your target pace. Use incline to increase difficulty without increasing speed. Hold onto rails only if needed for balance. Cool down by gradually reducing speed.",
           ExerciseTrackingType::Cardio),
        ex_t("cardio-02", "Elliptical", Category::Cardio, Equipment::Machine,
           &["Cardio", "Legs", "Arms"],
           "Setup: Step onto the pedals while holding the stationary center handles for balance first. Once stable, grip the moving arm handles. Most ellipticals have resistance and incline controls on the center console. Adjust resistance to your level (start at 3-5). Execution: Stride in a smooth, oval motion — push with your legs and pull/push with your arms simultaneously. Keep your back straight and core engaged. You can reverse direction to target different muscles. The elliptical is low-impact, making it easier on joints than running. Most machines show stride rate (aim for 130-160 SPM for moderate effort).",
           ExerciseTrackingType::Cardio),
        ex_t("cardio-03", "Stationary Bike", Category::Cardio, Equipment::Machine,
           &["Cardio", "Quads", "Hamstrings"],
           "Setup: Adjust seat height so your leg has a slight bend (about 25-30 degrees) at the bottom of the pedal stroke — if your hips rock side to side, the seat is too high. For upright bikes, adjust handlebar height to a comfortable position. For recumbent bikes, adjust the seat distance so you have the same slight knee bend. Strap your feet into the pedals if clips are available. Execution: Start pedaling and adjust resistance using the console. Maintain a cadence of 60-90 RPM for steady state cardio. Keep your upper body relaxed, avoid gripping handlebars too tightly. Most bikes have preset programs for intervals, hills, etc.",
           ExerciseTrackingType::Cardio),
        ex_t("cardio-04", "Rowing Machine", Category::Cardio, Equipment::Machine,
           &["Cardio", "Back", "Legs", "Arms"],
           "Setup: Sit on the sliding seat and strap your feet into the footplates — the strap should go across the widest part of your foot (ball of foot area). Adjust the damper setting on the side of the fan (3-5 is good for most people; higher is not necessarily harder, it changes the feel). Grip the handle with an overhand grip. Execution: The stroke has 4 phases — Catch: slide forward, shins vertical, arms straight. Drive: push with legs first (60% of power), then lean back slightly, then pull handle to lower ribs. Finish: legs straight, slight lean back, handle at lower ribs. Recovery: extend arms, lean forward, bend knees, slide to catch. Keep the chain level throughout.",
           ExerciseTrackingType::Cardio),
        ex_t("cardio-05", "Stair Climber", Category::Cardio, Equipment::Machine,
           &["Cardio", "Quads", "Glutes", "Calves"],
           "Setup: Step onto the machine while holding the side rails. Most stair climbers have rotating steps or pedal-style steps. Start at a slow speed (level 3-5) to find your rhythm before increasing. Execution: Step at a steady, consistent pace. Push through your whole foot, not just your toes. Stand upright — the most common mistake is leaning heavily on the rails, which reduces the workout significantly. Use rails for balance only with a light touch. Keep your core engaged and posture tall. For more glute activation, take deeper steps. Most machines display floors climbed and step rate.",
           ExerciseTrackingType::Cardio),
        ex_t("cardio-06", "Jump Rope", Category::Cardio, Equipment::Other,
           &["Cardio", "Calves", "Shoulders"],
           "Swing rope over head, jump with both feet. Keep jumps small and consistent.",
           ExerciseTrackingType::Bodyweight),
        ex_t("cardio-07", "Battle Ropes", Category::Cardio, Equipment::Other,
           &["Cardio", "Arms", "Shoulders", "Core"],
           "Hold rope ends. Make alternating or simultaneous waves with intensity.",
           ExerciseTrackingType::Bodyweight),
        ex_t("cardio-08", "Burpees", Category::Cardio, Equipment::Bodyweight,
           &["Cardio", "Full Body"],
           "Squat, kick feet back to push-up, jump feet forward, jump up with arms overhead.",
           ExerciseTrackingType::Bodyweight),
    ]
}
