use crate::models::{Category, Equipment, Exercise, ExerciseTrackingType};

fn ex(
    id: &str,
    name: &str,
    cat: Category,
    equip: Equipment,
    muscles: &[&str],
    desc: &str,
) -> Exercise {
    ex_t(
        id,
        name,
        cat,
        equip,
        muscles,
        desc,
        ExerciseTrackingType::Strength,
    )
}

fn ex_t(
    id: &str,
    name: &str,
    cat: Category,
    equip: Equipment,
    muscles: &[&str],
    desc: &str,
    tt: ExerciseTrackingType,
) -> Exercise {
    // Default to .svg, but allowing contributors to easily change extensions here
    let image_path = format!("icons/exercises/{}.svg", id);
    Exercise {
        id: id.to_string(),
        name: name.to_string(),
        category: cat,
        equipment: equip,
        muscle_groups: muscles.iter().map(|s| s.to_string()).collect(),
        description: desc.to_string(),
        is_custom: false,
        image: Some(image_path),
        tracking_type: tt,
    }
}

pub fn default_exercises() -> Vec<Exercise> {
    vec![
        // === CHEST ===
        ex("chest-01", "Barbell Bench Press", Category::Chest, Equipment::Barbell,
           &["Chest", "Triceps", "Front Delts"],
           "Lie on bench, grip bar slightly wider than shoulders. Lower to chest, press up to lockout."),
        ex("chest-02", "Incline Barbell Bench Press", Category::Chest, Equipment::Barbell,
           &["Upper Chest", "Triceps", "Front Delts"],
           "Set bench to 30-45 degrees. Lower bar to upper chest, press up."),
        ex("chest-03", "Decline Barbell Bench Press", Category::Chest, Equipment::Barbell,
           &["Lower Chest", "Triceps"],
           "Set bench to decline. Lower bar to lower chest, press up."),
        ex("chest-04", "Dumbbell Bench Press", Category::Chest, Equipment::Dumbbell,
           &["Chest", "Triceps", "Front Delts"],
           "Lie on bench with dumbbells. Press up, lower with control."),
        ex("chest-05", "Incline Dumbbell Press", Category::Chest, Equipment::Dumbbell,
           &["Upper Chest", "Triceps", "Front Delts"],
           "Incline bench at 30-45 degrees. Press dumbbells up from shoulders."),
        ex("chest-06", "Dumbbell Fly", Category::Chest, Equipment::Dumbbell,
           &["Chest"],
           "Lie on bench, arms extended with slight bend. Lower dumbbells in arc, squeeze back up."),
        ex("chest-07", "Cable Fly", Category::Chest, Equipment::Cable,
           &["Chest"],
           "Stand between cable stations. Bring handles together in front of chest with slight elbow bend."),
        ex("chest-08", "Pec Deck Machine", Category::Chest, Equipment::Machine,
           &["Chest"],
           "Setup: Adjust seat height so handles align with mid-chest. Set the arm pads or handles so your arms start at about 70-80 degrees out to your sides — you should feel a mild stretch but no shoulder strain. Sit with back flat against pad, feet flat on floor. Execution: Place forearms against pads (or grip handles). Bring arms together in front of chest in a hugging motion. Squeeze chest hard at the center, then return slowly to start. Keep a slight bend in elbows throughout. Avoid letting the weight stack slam at the bottom."),
        ex("chest-09", "Machine Chest Press", Category::Chest, Equipment::Machine,
           &["Chest", "Triceps", "Front Delts"],
           "Setup: Adjust seat height so the handles line up with your mid-to-lower chest (nipple line). Your feet should be flat on the floor. Sit with back firmly against the pad and grip the handles. Some machines have a foot lever to bring the handles into starting position — use it to avoid straining your shoulders. Execution: Press handles forward until arms are nearly straight but not locked out. Return slowly until you feel a stretch across the chest. Keep shoulder blades pinched back against the pad throughout. Don't arch your lower back off the seat."),
        ex_t("chest-10", "Push-ups", Category::Chest, Equipment::Bodyweight,
           &["Chest", "Triceps", "Front Delts", "Core"],
           "Hands shoulder-width apart, body straight. Lower chest to ground, push back up.",
           ExerciseTrackingType::Bodyweight),
        ex_t("chest-11", "Dips (Chest)", Category::Chest, Equipment::Bodyweight,
           &["Lower Chest", "Triceps", "Front Delts"],
           "Lean forward on parallel bars. Lower body until upper arms are parallel, press up.",
           ExerciseTrackingType::Bodyweight),
        ex("chest-12", "Cable Crossover", Category::Chest, Equipment::Cable,
           &["Chest"],
           "Set cables high. Step forward, bring handles down and together in arc."),
        ex("chest-13", "Smith Machine Bench Press", Category::Chest, Equipment::Machine,
           &["Chest", "Triceps", "Front Delts"],
           "Lie on bench under Smith machine bar. Unrack, lower to chest, press up to lockout."),
        ex("chest-14", "Decline Dumbbell Press", Category::Chest, Equipment::Dumbbell,
           &["Lower Chest", "Triceps"],
           "Set bench to decline. Hold dumbbells at chest level, press up, lower with control."),
        ex_t("chest-15", "Diamond Push-up", Category::Chest, Equipment::Bodyweight,
           &["Triceps", "Chest", "Front Delts"],
           "Place hands together under your chest forming a diamond shape with thumbs and index fingers. Lower your chest to your hands, then push back up. Emphasizes triceps more than standard push-ups.",
           ExerciseTrackingType::Bodyweight),
        ex_t("chest-16", "Pike Push-up", Category::Chest, Equipment::Bodyweight,
           &["Front Delts", "Triceps", "Chest"],
           "Start in a push-up position then walk your feet toward your hands, raising your hips into an inverted V. Bend your elbows to lower your head toward the ground, then press back up. A progression toward handstand push-ups.",
           ExerciseTrackingType::Bodyweight),
        ex_t("chest-17", "Archer Push-up", Category::Chest, Equipment::Bodyweight,
           &["Chest", "Triceps"],
           "Start in a wide push-up position. As you lower, shift your weight to one arm while extending the other arm out straight. Push back up and alternate sides.",
           ExerciseTrackingType::Bodyweight),

        // === BACK ===
        ex("back-01", "Lat Pulldown", Category::Back, Equipment::Cable,
           &["Lats", "Biceps", "Rear Delts"],
           "Setup: Attach a wide bar to the high cable. Adjust the thigh pad so it sits snugly on your thighs when seated — this keeps you from lifting off the seat during heavy pulls. Sit down and grip the bar wider than shoulder-width with an overhand grip. Execution: Pull the bar down to your upper chest, driving your elbows down and back. Squeeze your lats at the bottom, then return the bar up with control until your arms are fully extended and you feel a stretch in your lats. Keep your torso upright or with only a very slight lean back. Avoid pulling behind the neck — always pull to the front."),
        ex("back-02", "Seated Cable Row", Category::Back, Equipment::Cable,
           &["Mid Back", "Lats", "Biceps", "Rear Delts"],
           "Setup: Attach a V-handle or close-grip handle to the low cable. Sit on the bench with feet on the foot platform, knees slightly bent. Reach forward to grab the handle. Start with arms extended, slight forward lean, back straight. Execution: Pull the handle to your lower chest/upper abdomen, driving elbows back past your torso. Squeeze your shoulder blades together at full contraction. Return with control, letting your arms extend and shoulders stretch forward slightly. Keep your lower back neutral — don't round or excessively arch. The torso should stay mostly upright; a small amount of controlled lean is acceptable."),
        ex("back-03", "Barbell Bent-over Row", Category::Back, Equipment::Barbell,
           &["Mid Back", "Lats", "Biceps", "Rear Delts"],
           "Hinge at hips, back flat. Pull barbell to lower chest, squeeze back."),
        ex("back-04", "Dumbbell Row", Category::Back, Equipment::Dumbbell,
           &["Lats", "Mid Back", "Biceps"],
           "One hand on bench, row dumbbell to hip. Keep elbow close to body."),
        ex("back-05", "Deadlift", Category::Back, Equipment::Barbell,
           &["Lower Back", "Glutes", "Hamstrings", "Traps"],
           "Stand over bar, hip-width grip. Drive through heels, extend hips and knees together."),
        ex("back-06", "Romanian Deadlift", Category::Back, Equipment::Barbell,
           &["Hamstrings", "Lower Back", "Glutes"],
           "Hold bar at hips. Hinge forward keeping legs nearly straight, lower to mid-shin."),
        ex_t("back-07", "Pull-ups", Category::Back, Equipment::Bodyweight,
           &["Lats", "Biceps", "Rear Delts"],
           "Grip bar overhand wider than shoulders. Pull chin over bar, lower with control.",
           ExerciseTrackingType::Bodyweight),
        ex_t("back-08", "Chin-ups", Category::Back, Equipment::Bodyweight,
           &["Lats", "Biceps"],
           "Grip bar underhand shoulder-width. Pull chin over bar, lower with control.",
           ExerciseTrackingType::Bodyweight),
        ex("back-09", "T-Bar Row", Category::Back, Equipment::Barbell,
           &["Mid Back", "Lats", "Biceps"],
           "Straddle T-bar, grip handle. Pull to chest, squeeze back, lower with control."),
        ex("back-10", "Cable Pullover", Category::Back, Equipment::Cable,
           &["Lats"],
           "Face cable machine, grip bar overhead. Pull down in arc to thighs, keeping arms straight."),
        ex("back-11", "Machine Row", Category::Back, Equipment::Machine,
           &["Mid Back", "Lats", "Biceps"],
           "Setup: Adjust the chest pad so you can fully extend your arms and just barely reach the handles. Adjust seat height so the handles are at lower chest or upper abdomen level. Sit with chest firmly pressed into the pad, feet flat on the floor or on the foot platform. Execution: Pull handles toward your torso, driving elbows back. Squeeze shoulder blades together at the end of the pull — hold for a beat. Return with control, letting your arms fully extend to stretch the lats. Keep chest against the pad throughout; don't lean back to cheat the weight."),
        ex_t("back-12", "Hyperextension", Category::Back, Equipment::Bodyweight,
           &["Lower Back", "Glutes", "Hamstrings"],
           "Lock feet in hyperextension bench. Lower torso, extend back to straight position.",
           ExerciseTrackingType::Bodyweight),
        ex("back-13", "Vertical Traction", Category::Back, Equipment::Machine,
           &["Lats", "Biceps", "Rear Delts"],
           "Setup: Adjust the thigh pad so it sits snugly on your thighs when seated. Grip the close/neutral handles. Execution: Pull handles down to upper chest, driving elbows down and close to your body. Squeeze lats at the bottom, then return with control until arms are fully extended. The close grip and converging path emphasize the lower lats more than a wide-grip lat pulldown."),
        ex("back-14", "Seated Back Extension", Category::Back, Equipment::Machine,
           &["Lower Back", "Erector Spinae"],
           "Setup: Adjust the foot platform and back pad so the pivot point aligns with your hips. Sit with upper back against the pad and feet on the platform. Cross arms over chest or grip the handles. Execution: Push back against the pad, extending your torso until your back is straight or slightly past straight. Return slowly to the starting position. Keep the movement controlled — avoid using momentum."),
        ex("back-15", "Assisted Chin/Dip", Category::Back, Equipment::Machine,
           &["Lats", "Biceps", "Triceps", "Chest"],
           "Setup: Select the counterweight — higher weight means more assistance. Step onto the platform or kneel on the pad. Grip the chin-up or dip handles. Execution: For chin-ups, pull yourself up until chin is over the bar. For dips, lower yourself until upper arms are parallel, then press up. The machine offsets your bodyweight, making the movement easier. Reduce the counterweight as you get stronger."),
        ex("back-16", "Dumbbell Pullover", Category::Back, Equipment::Dumbbell,
           &["Lats", "Chest", "Triceps"],
           "Lie across a bench with upper back supported. Hold one dumbbell overhead with both hands, arms slightly bent. Lower the weight behind your head in an arc until you feel a stretch in your lats. Pull the weight back over your chest. Keep your hips low and core tight."),
        ex("back-17", "Straight Arm Pulldown", Category::Back, Equipment::Cable,
           &["Lats"],
           "Stand facing a high cable with a straight bar or rope attachment. With arms nearly straight and a slight bend in the elbows, pull the bar down in an arc to your thighs. Squeeze your lats at the bottom, then return with control. Keep your torso slightly hinged forward and avoid using momentum."),
        ex_t("back-18", "Inverted Row", Category::Back, Equipment::Bodyweight,
           &["Lats", "Traps", "Biceps", "Rear Delts"],
           "Set a bar at waist height (Smith machine or rack). Hang underneath with arms extended, body straight. Pull your chest to the bar, squeezing your back, then lower with control.",
           ExerciseTrackingType::Bodyweight),
        ex_t("back-19", "Muscle-up", Category::Back, Equipment::Bodyweight,
           &["Lats", "Biceps", "Chest", "Triceps"],
           "Hang from a pull-up bar. Explosively pull yourself up and over the bar, transitioning from a pull-up into a dip position above the bar. Press to full lockout, then lower with control.",
           ExerciseTrackingType::Bodyweight),
        ex_t("back-20", "Archer Pull-up", Category::Back, Equipment::Bodyweight,
           &["Lats", "Biceps"],
           "Grip a pull-up bar wide. Pull yourself up toward one hand while extending the other arm straight along the bar. Lower with control and alternate sides.",
           ExerciseTrackingType::Bodyweight),

        // === LEGS ===
        ex("legs-01", "Barbell Squat", Category::Legs, Equipment::Barbell,
           &["Quads", "Glutes", "Hamstrings", "Core"],
           "Bar on upper back, feet shoulder-width. Squat to parallel or below, drive up."),
        ex("legs-02", "Front Squat", Category::Legs, Equipment::Barbell,
           &["Quads", "Glutes", "Core"],
           "Bar on front delts, elbows high. Squat keeping torso upright, drive up."),
        ex("legs-03", "Leg Press", Category::Legs, Equipment::Machine,
           &["Quads", "Glutes", "Hamstrings"],
           "Setup: Sit in the sled with your back and hips flat against the pad. Place feet shoulder-width on the platform — higher foot placement targets glutes/hamstrings more, lower placement targets quads more. Adjust the safety catches so you can reach full depth without rounding your lower back. Unlock the sled by turning the side handles. Execution: Lower the sled by bending your knees toward your chest until you reach about 90 degrees. Press through your whole foot back to the starting position. Don't lock knees at the top. Keep your lower back pressed into the seat throughout — if your hips curl up at the bottom, you're going too deep."),
        ex("legs-04", "Leg Extension", Category::Legs, Equipment::Machine,
           &["Quads"],
           "Setup: Adjust the backrest so your knees align with the machine's pivot point (usually marked with a dot or line on the side). Adjust the shin pad so it sits just above your ankles on the front of your lower legs. Set the starting position so your knees are at about 90 degrees. Sit with back against pad, grip the side handles. Execution: Extend your legs until they're straight, squeezing your quads hard at the top. Hold for a beat, then lower with control — don't let the weight drop. Avoid swinging or using momentum. For knee safety, don't go excessively heavy; focus on controlled reps."),
        ex("legs-05", "Leg Curl (Lying)", Category::Legs, Equipment::Machine,
           &["Hamstrings"],
           "Setup: Lie face down on the bench. Adjust the leg pad so it sits just above your ankles on the back of your lower legs. Your knees should be just off the edge of the bench and aligned with the machine's pivot point. Grip the handles under the bench. Execution: Curl your heels toward your glutes, squeezing hamstrings at the top. Lower with a slow, controlled tempo — don't let the weight slam down. Keep your hips pressed against the bench; if they rise, the weight is too heavy. Point your toes slightly away from you to better engage the hamstrings."),
        ex("legs-06", "Leg Curl (Seated)", Category::Legs, Equipment::Machine,
           &["Hamstrings"],
           "Setup: Adjust the backrest so your knees align with the machine's pivot point. Set the upper thigh pad snug against your thighs just above the knees — it should hold you down but not be uncomfortably tight. Adjust the lower leg pad to sit just above your ankles on the back of your legs. Start with legs extended. Execution: Curl your legs down and back, pulling heels under the seat. Squeeze hamstrings at full contraction, then return with control to the start. Keep your back against the pad throughout and avoid jerking the weight."),
        ex("legs-07", "Hack Squat", Category::Legs, Equipment::Machine,
           &["Quads", "Glutes"],
           "Setup: Step onto the platform and place your back against the sliding pad. Position shoulders under the shoulder pads. Place feet shoulder-width on the platform — foot position affects targeting just like the leg press. Release the safety handles on the sides. Execution: Lower your body by bending knees to about 90 degrees (or deeper if comfortable). Drive through your feet to push back up. Keep your back flat against the pad at all times. Don't lock knees at the top. Re-engage the safety handles when finished."),
        ex("legs-08", "Bulgarian Split Squat", Category::Legs, Equipment::Dumbbell,
           &["Quads", "Glutes", "Hamstrings"],
           "Rear foot on bench, front foot forward. Lower until front thigh is parallel, drive up."),
        ex("legs-09", "Walking Lunges", Category::Legs, Equipment::Dumbbell,
           &["Quads", "Glutes", "Hamstrings"],
           "Step forward into lunge, knee to 90 degrees. Push off front foot, step into next lunge."),
        ex("legs-10", "Calf Raise (Standing)", Category::Legs, Equipment::Machine,
           &["Calves"],
           "Setup: Step under the shoulder pads and stand on the edge of the foot platform with the balls of your feet. Your heels should hang off the edge. Adjust the shoulder pad height so you're standing straight with a slight knee bend. Execution: Rise up onto your toes as high as possible, squeezing your calves at the top. Hold for a beat, then lower your heels below the platform level for a deep stretch. Keep the movement slow and controlled — avoid bouncing. Keep knees slightly bent and body upright throughout."),
        ex("legs-11", "Calf Raise (Seated)", Category::Legs, Equipment::Machine,
           &["Calves"],
           "Setup: Sit on the machine and place the balls of your feet on the foot platform with heels hanging off. Adjust the knee pad so it sits snugly on your lower thighs just above the knees — tight enough to hold you down but not painful. Release the safety bar. Execution: Press up through your toes as high as possible, squeezing calves at the top. Lower your heels slowly below the platform for a full stretch. The seated position primarily targets the soleus (deeper calf muscle) while standing targets the gastrocnemius (outer calf)."),
        ex("legs-12", "Goblet Squat", Category::Legs, Equipment::Dumbbell,
           &["Quads", "Glutes", "Core"],
           "Hold dumbbell at chest. Squat deep keeping torso upright, drive up."),
        ex("legs-13", "Hip Thrust", Category::Legs, Equipment::Barbell,
           &["Glutes", "Hamstrings"],
           "Upper back on bench, bar over hips. Drive hips up to full extension, squeeze glutes."),
        ex("legs-18", "Multi Hip", Category::Legs, Equipment::Machine,
           &["Glutes", "Hip Flexors", "Hip Abductors", "Hip Adductors"],
           "Setup: Adjust the thigh pad height and the range of motion stops. Stand on the platform and place one leg against the roller pad. Hold the handles for stability. Execution: Move your leg in the selected direction — forward (hip flexion), backward (hip extension), or to the side (abduction/adduction). Switch legs after completing your set. This machine trains all hip movements on one station."),
        ex("legs-19", "Hip Thrust Machine", Category::Legs, Equipment::Machine,
           &["Glutes", "Hamstrings"],
           "Setup: Sit on the machine with your upper back against the pad. Place feet flat on the foot platform at shoulder width. Adjust the hip pad so it sits across your hip crease. Execution: Drive your hips up by squeezing your glutes until your body forms a straight line from shoulders to knees. Hold at the top for a beat, then lower with control. Keep your chin slightly tucked and avoid hyperextending your lower back at the top."),
        ex("legs-14", "Leg Press Calf Raise", Category::Legs, Equipment::Machine,
           &["Calves"],
           "Setup: Sit in the leg press with back and hips flat against the pad. Place only the balls of your feet and toes on the very bottom edge of the foot platform — heels should be off the platform entirely. Use a lighter weight than your normal leg press. Unlock the sled and press to a nearly straight leg position (this is your starting position). Execution: Push through your toes to extend your ankles, then slowly allow your toes to come back toward you for a stretch. Keep the sled locked out at the knees — all movement is at the ankle joint. Keep safety catches engaged close by."),
        ex("legs-15", "Smith Machine Squat", Category::Legs, Equipment::Machine,
           &["Quads", "Glutes"],
           "Setup: Set the bar at upper chest height on the Smith machine. Step under the bar and position it across your upper traps (not your neck). Place feet shoulder-width apart, slightly in front of the bar — this is different from free squats because the bar path is fixed. Twist the bar to unhook it from the safety catches. Set the safety stops at a height just below your lowest squat depth. Execution: Squat down by bending knees and hips until thighs are at least parallel. Drive up through your feet. The fixed bar path means you can lean back slightly and emphasize quads. Re-rack by twisting the bar back into the hooks."),
        ex("legs-16", "Hip Abductor", Category::Legs, Equipment::Machine,
           &["Glutes", "Hip Abductors"],
           "Sit with pads on outer thighs. Push legs apart against resistance, return with control."),
        ex("legs-17", "Hip Adductor", Category::Legs, Equipment::Machine,
           &["Inner Thighs", "Hip Adductors"],
           "Sit with pads on inner thighs. Squeeze legs together against resistance, return with control."),
        ex("legs-20", "Sumo Deadlift", Category::Legs, Equipment::Barbell,
           &["Quads", "Glutes", "Hamstrings", "Inner Thighs"],
           "Stand with a wide stance, toes pointed out. Grip the bar between your legs with a narrow grip. Drive through your heels, extending hips and knees together. Keep chest up and back flat throughout."),
        ex("legs-21", "Reverse Lunge", Category::Legs, Equipment::Dumbbell,
           &["Quads", "Glutes", "Hamstrings"],
           "Stand with dumbbells at sides. Step one foot backward into a lunge, lowering until front thigh is parallel. Push through the front foot to return to standing. Alternate legs."),
        ex_t("legs-22", "Step-ups", Category::Legs, Equipment::Dumbbell,
           &["Quads", "Glutes"],
           "Hold dumbbells at sides. Step one foot onto a bench or box. Drive through that foot to stand up fully on the box. Step down with control. Complete all reps on one side, then switch.",
           ExerciseTrackingType::Strength),
        ex_t("legs-23", "Nordic Hamstring Curl", Category::Legs, Equipment::Bodyweight,
           &["Hamstrings"],
           "Kneel on a pad with ankles secured (under a bar or held by a partner). Slowly lower your torso toward the ground by extending at the knees, keeping hips straight. Use your hamstrings to control the descent. Push off the ground lightly to return to the starting position.",
           ExerciseTrackingType::Bodyweight),
        ex("legs-24", "Glute Kickback Machine", Category::Legs, Equipment::Machine,
           &["Glutes", "Hamstrings"],
           "Setup: Adjust the thigh pad and foot plate height. Stand on one leg on the platform and place the other foot against the foot plate. Grip the handles for stability. Execution: Push the foot plate backward by extending your hip, squeezing your glute at full extension. Return with control. Complete all reps on one side, then switch."),
        ex("legs-25", "Pendulum Squat", Category::Legs, Equipment::Machine,
           &["Quads", "Glutes"],
           "Setup: Step onto the platform and place shoulders under the pads. Position feet at the bottom of the platform for more quad emphasis, or higher for more glute emphasis. Execution: Squat down by bending knees, keeping back against the pad. The pendulum path allows deep squatting with less lower back stress than a traditional squat. Drive up through your feet."),
        ex("legs-26", "Belt Squat", Category::Legs, Equipment::Machine,
           &["Quads", "Glutes", "Hamstrings"],
           "Setup: Attach the belt around your hips and connect it to the machine's loading mechanism. Stand on the platforms with feet shoulder-width apart. Execution: Squat down to parallel or below, then drive up. The belt squat loads your legs without compressing your spine, making it ideal for those with back issues or as a high-volume squat alternative."),
        ex_t("legs-27", "Pistol Squat", Category::Legs, Equipment::Bodyweight,
           &["Quads", "Glutes", "Core"],
           "Stand on one leg with the other extended in front. Squat down on the standing leg until your hip crease is below your knee, then drive back up. Keep your arms forward for balance.",
           ExerciseTrackingType::Bodyweight),
        ex_t("legs-28", "Glute Bridge", Category::Legs, Equipment::Bodyweight,
           &["Glutes", "Hamstrings"],
           "Lie on your back with knees bent and feet flat on the floor. Drive through your heels to lift your hips until your body forms a straight line from shoulders to knees. Squeeze glutes at the top, then lower with control.",
           ExerciseTrackingType::Bodyweight),
        ex_t("legs-29", "Wall Sit", Category::Legs, Equipment::Bodyweight,
           &["Quads"],
           "Stand with your back against a wall. Slide down until your thighs are parallel to the ground, knees at 90 degrees. Hold the position with your back flat against the wall.",
           ExerciseTrackingType::Duration),
        ex_t("legs-30", "Box Jump", Category::Legs, Equipment::Bodyweight,
           &["Quads", "Glutes", "Calves"],
           "Stand facing a sturdy box or platform. Swing your arms and jump explosively onto the box, landing softly with both feet. Stand up fully, then step down. Focus on soft landings.",
           ExerciseTrackingType::Bodyweight),
        ex_t("legs-31", "Jump Squat", Category::Legs, Equipment::Bodyweight,
           &["Quads", "Glutes", "Calves"],
           "Stand with feet shoulder-width apart. Squat down, then explode upward into a jump. Land softly and immediately descend into the next rep.",
           ExerciseTrackingType::Bodyweight),
        ex_t("legs-32", "Cossack Squat", Category::Legs, Equipment::Bodyweight,
           &["Quads", "Glutes", "Hamstrings"],
           "Stand with a wide stance. Shift your weight to one side, squatting down on that leg while keeping the other leg straight. Alternate sides.",
           ExerciseTrackingType::Bodyweight),

        // === SHOULDERS ===
        ex("shldr-01", "Overhead Press (Barbell)", Category::Shoulders, Equipment::Barbell,
           &["Front Delts", "Side Delts", "Triceps"],
           "Bar at shoulder height. Press overhead to lockout, lower to shoulders."),
        ex("shldr-02", "Dumbbell Shoulder Press", Category::Shoulders, Equipment::Dumbbell,
           &["Front Delts", "Side Delts", "Triceps"],
           "Dumbbells at shoulders. Press overhead, lower with control."),
        ex("shldr-03", "Lateral Raise", Category::Shoulders, Equipment::Dumbbell,
           &["Side Delts"],
           "Dumbbells at sides. Raise arms out to sides until parallel to ground, lower with control."),
        ex("shldr-04", "Front Raise", Category::Shoulders, Equipment::Dumbbell,
           &["Front Delts"],
           "Dumbbells in front of thighs. Raise one or both arms to shoulder height, lower."),
        ex("shldr-05", "Face Pull", Category::Shoulders, Equipment::Cable,
           &["Rear Delts", "Traps", "Rotator Cuff"],
           "Cable at face height with rope. Pull to face, externally rotate, squeeze rear delts."),
        ex("shldr-06", "Rear Delt Fly (Dumbbell)", Category::Shoulders, Equipment::Dumbbell,
           &["Rear Delts"],
           "Bend forward, dumbbells hanging. Raise arms out to sides, squeeze rear delts."),
        ex("shldr-07", "Machine Shoulder Press", Category::Shoulders, Equipment::Machine,
           &["Front Delts", "Side Delts", "Triceps"],
           "Setup: Adjust the seat height so the handles start at about ear level when seated. Your upper arms should be roughly parallel to the ground in the starting position. Sit with back firmly against the pad and feet flat on the floor. Grip the handles — most machines offer both a wide and narrow grip; the wider grip emphasizes side delts more. Execution: Press the handles overhead until arms are nearly straight but not locked out. Lower with control back to the starting position. Keep your back against the pad; don't arch excessively. Keep your core braced throughout."),
        ex("shldr-08", "Cable Lateral Raise", Category::Shoulders, Equipment::Cable,
           &["Side Delts"],
           "Stand next to low cable. Raise arm out to side to shoulder height."),
        ex("shldr-09", "Arnold Press", Category::Shoulders, Equipment::Dumbbell,
           &["Front Delts", "Side Delts", "Triceps"],
           "Start with palms facing you at shoulders. Rotate and press overhead."),
        ex("shldr-10", "Upright Row", Category::Shoulders, Equipment::Barbell,
           &["Side Delts", "Traps"],
           "Grip bar narrow. Pull up along body to chin height, elbows leading."),
        ex("shldr-11", "Reverse Pec Deck", Category::Shoulders, Equipment::Machine,
           &["Rear Delts"],
           "Setup: This uses the same machine as the Pec Deck but facing the opposite direction. Adjust the seat so the handles are at shoulder height when seated. Sit facing the pad with your chest against it. Grip the handles with a neutral or overhand grip — arms should be extended in front of you. Some machines have specific rear delt handles; use those if available. Execution: Push the handles back and out in a reverse fly motion, squeezing your rear delts and upper back at full contraction. Return slowly to start. Keep a slight bend in the elbows throughout. Don't lean back or use momentum."),
        ex("shldr-12", "Shrugs (Barbell)", Category::Shoulders, Equipment::Barbell,
           &["Traps"],
           "Hold barbell at thighs. Shrug shoulders up toward ears, hold, lower."),
        ex("shldr-13", "Shrugs (Dumbbell)", Category::Shoulders, Equipment::Dumbbell,
           &["Traps"],
           "Hold dumbbells at sides. Shrug shoulders up toward ears, hold, lower."),
        ex("shldr-14", "Machine Lateral Raise", Category::Shoulders, Equipment::Machine,
           &["Side Delts"],
           "Setup: Adjust the seat height so the pivot point aligns with your shoulder joints. Sit with back against the pad and place the outside of your upper arms against the arm pads. Execution: Raise your arms out to the sides until they are parallel to the ground. Hold briefly at the top, then lower with control. Keep a slight bend in your elbows and avoid shrugging your traps."),
        ex("shldr-15", "Landmine Press", Category::Shoulders, Equipment::Barbell,
           &["Front Delts", "Upper Chest", "Triceps"],
           "Place one end of a barbell in a landmine attachment or corner. Hold the other end at shoulder height with one or both hands. Press the bar up and forward at an angle until your arm is extended. Lower with control. The angled pressing path is easier on the shoulders than a strict overhead press."),
        ex_t("shldr-16", "Handstand Push-up", Category::Shoulders, Equipment::Bodyweight,
           &["Front Delts", "Side Delts", "Triceps"],
           "Kick up into a handstand against a wall. Lower yourself by bending your elbows until your head lightly touches the ground, then press back up. Keep your core tight and body straight.",
           ExerciseTrackingType::Bodyweight),

        // === ARMS ===
        ex("arms-01", "Barbell Curl", Category::Arms, Equipment::Barbell,
           &["Biceps"],
           "Stand with barbell, underhand grip. Curl to shoulders keeping elbows fixed, lower."),
        ex("arms-02", "Dumbbell Curl", Category::Arms, Equipment::Dumbbell,
           &["Biceps"],
           "Stand with dumbbells. Curl to shoulders, lower with control. Alternate or together."),
        ex("arms-03", "Hammer Curl", Category::Arms, Equipment::Dumbbell,
           &["Biceps", "Brachialis", "Forearms"],
           "Hold dumbbells with neutral grip. Curl up keeping palms facing each other, lower."),
        ex("arms-04", "Preacher Curl", Category::Arms, Equipment::Barbell,
           &["Biceps"],
           "Arms on preacher bench pad. Curl bar up, lower with full extension."),
        ex("arms-05", "Cable Curl", Category::Arms, Equipment::Cable,
           &["Biceps"],
           "Face low cable with bar attachment. Curl up, squeeze biceps, lower with control."),
        ex("arms-06", "Concentration Curl", Category::Arms, Equipment::Dumbbell,
           &["Biceps"],
           "Sit, elbow on inner thigh. Curl dumbbell to shoulder, squeeze, lower."),
        ex("arms-07", "Tricep Pushdown", Category::Arms, Equipment::Cable,
           &["Triceps"],
           "Face high cable with bar/rope. Push down to full extension, return with control."),
        ex("arms-08", "Overhead Tricep Extension", Category::Arms, Equipment::Dumbbell,
           &["Triceps"],
           "Hold dumbbell overhead with both hands. Lower behind head, extend back up."),
        ex("arms-09", "Skull Crushers", Category::Arms, Equipment::Barbell,
           &["Triceps"],
           "Lie on bench, bar overhead. Lower to forehead bending elbows, extend back up."),
        ex_t("arms-10", "Tricep Dips", Category::Arms, Equipment::Bodyweight,
           &["Triceps", "Chest", "Front Delts"],
           "On parallel bars, body upright. Lower body bending elbows, press back up.",
           ExerciseTrackingType::Bodyweight),
        ex("arms-11", "Cable Overhead Extension", Category::Arms, Equipment::Cable,
           &["Triceps"],
           "Face away from low cable with rope. Extend arms overhead, squeeze triceps."),
        ex("arms-12", "Close-Grip Bench Press", Category::Arms, Equipment::Barbell,
           &["Triceps", "Chest"],
           "Lie on bench, narrow grip on bar. Lower to chest, press up focusing on triceps."),
        ex("arms-13", "Wrist Curl", Category::Arms, Equipment::Dumbbell,
           &["Forearms"],
           "Sit with forearms on thighs, palms up. Curl wrists up, lower with control."),
        ex("arms-14", "Reverse Curl", Category::Arms, Equipment::Barbell,
           &["Forearms", "Biceps"],
           "Stand with barbell, overhand grip. Curl up keeping overhand grip, lower."),
        ex("arms-15", "Machine Bicep Curl", Category::Arms, Equipment::Machine,
           &["Biceps"],
           "Setup: Adjust the seat height so your upper arms rest flat on the pad with elbows aligned to the machine's pivot point. Grip the handles with an underhand grip. Execution: Curl the handles toward your shoulders, squeezing your biceps at the top. Lower with control until arms are nearly fully extended. Keep your upper arms pressed against the pad throughout — don't lift your elbows."),
        ex("arms-16", "Machine Tricep Extension", Category::Arms, Equipment::Machine,
           &["Triceps"],
           "Setup: Adjust the seat so your elbows align with the machine's pivot point. Place the backs of your upper arms against the pad and grip the handles. Execution: Extend your arms downward, straightening at the elbow. Squeeze your triceps at full extension, then return with control. Keep your upper arms against the pad — all movement should be at the elbow joint."),
        ex("arms-17", "Incline Dumbbell Curl", Category::Arms, Equipment::Dumbbell,
           &["Biceps"],
           "Set bench to 45-60 degree incline. Sit back with dumbbells hanging at your sides. Curl up, squeezing biceps at the top, then lower with control. The incline stretches the long head of the biceps more than a standing curl."),
        ex("arms-18", "EZ Bar Curl", Category::Arms, Equipment::Barbell,
           &["Biceps"],
           "Stand holding an EZ curl bar on the angled grips. Curl the bar to your shoulders keeping elbows at your sides. Lower with control. The angled grip reduces wrist strain compared to a straight barbell curl."),
        ex("arms-19", "Tricep Kickback", Category::Arms, Equipment::Dumbbell,
           &["Triceps"],
           "Hinge forward at hips or place one knee on a bench. Hold a dumbbell with elbow bent at 90 degrees, upper arm parallel to torso. Extend your forearm backward until your arm is straight, squeeze tricep, then return with control."),
        ex("arms-20", "Spider Curl", Category::Arms, Equipment::Dumbbell,
           &["Biceps"],
           "Lie face down on an incline bench set to about 45 degrees. Let your arms hang straight down holding dumbbells. Curl up, squeezing at the top, then lower with control. The angle keeps constant tension on the biceps throughout the movement."),

        // === CORE ===
        ex_t("core-01", "Plank", Category::Core, Equipment::Bodyweight,
           &["Core", "Abs", "Lower Back"],
           "Forearms and toes on ground, body straight. Hold position, keep core tight.",
           ExerciseTrackingType::Duration),
        ex_t("core-02", "Crunches", Category::Core, Equipment::Bodyweight,
           &["Abs"],
           "Lie on back, knees bent. Curl shoulders off ground, squeeze abs, lower.",
           ExerciseTrackingType::Bodyweight),
        ex_t("core-03", "Hanging Leg Raise", Category::Core, Equipment::Bodyweight,
           &["Lower Abs", "Hip Flexors"],
           "Hang from bar. Raise legs to parallel or higher, lower with control.",
           ExerciseTrackingType::Bodyweight),
        ex("core-04", "Cable Crunch", Category::Core, Equipment::Cable,
           &["Abs"],
           "Kneel at cable machine with rope at head. Crunch down, squeeze abs, return."),
        ex_t("core-05", "Russian Twist", Category::Core, Equipment::Bodyweight,
           &["Obliques", "Abs"],
           "Sit with feet off ground, lean back slightly. Rotate torso side to side.",
           ExerciseTrackingType::Bodyweight),
        ex("core-06", "Ab Wheel Rollout", Category::Core, Equipment::Other,
           &["Abs", "Core"],
           "Kneel with ab wheel. Roll forward extending body, pull back using abs."),
        ex_t("core-07", "Mountain Climbers", Category::Core, Equipment::Bodyweight,
           &["Core", "Hip Flexors", "Cardio"],
           "Push-up position. Alternate driving knees to chest rapidly.",
           ExerciseTrackingType::Bodyweight),
        ex_t("core-08", "Side Plank", Category::Core, Equipment::Bodyweight,
           &["Obliques", "Core"],
           "Lie on side, forearm on ground. Lift hips, body straight. Hold position.",
           ExerciseTrackingType::Duration),
        ex_t("core-09", "Bicycle Crunch", Category::Core, Equipment::Bodyweight,
           &["Abs", "Obliques"],
           "Lie on back, hands behind head. Alternate elbow to opposite knee in pedaling motion.",
           ExerciseTrackingType::Bodyweight),
        ex_t("core-10", "Dead Bug", Category::Core, Equipment::Bodyweight,
           &["Core", "Abs"],
           "Lie on back, arms up, knees at 90. Extend opposite arm and leg, return, alternate.",
           ExerciseTrackingType::Bodyweight),
        ex_t("core-11", "Decline Sit-up", Category::Core, Equipment::Bodyweight,
           &["Abs", "Hip Flexors"],
           "Lie on decline bench, feet hooked. Sit up fully, lower with control.",
           ExerciseTrackingType::Bodyweight),
        ex("core-12", "Abdominal Crunch Machine", Category::Core, Equipment::Machine,
           &["Abs"],
           "Setup: Adjust the seat height so the pivot point aligns with your mid-torso. Sit with back against the pad and grip the handles or place arms behind the pads. Execution: Crunch forward by contracting your abs, bringing your chest toward your knees. Hold the contraction briefly, then return slowly to the starting position. Keep the movement controlled — avoid using your arms to pull the weight."),
        ex("core-13", "Total Abdominal Machine", Category::Core, Equipment::Machine,
           &["Abs", "Lower Abs", "Hip Flexors"],
           "Setup: Sit on the machine with back against the pad. Grip the upper handles and place your shins behind the lower pads. Execution: Simultaneously crunch your upper body down and bring your knees up, contracting your entire abdominal wall. Return with control. This machine works both the upper and lower abs in one movement, unlike a standard crunch machine."),
        ex("core-14", "Rotary Torso Machine", Category::Core, Equipment::Machine,
           &["Obliques", "Core"],
           "Setup: Adjust the seat so the pivot point aligns with your spine. Sit with chest against the pad and grip the handles. Select your rotation direction. Execution: Rotate your torso against the resistance, keeping your hips fixed and facing forward. Return slowly to the starting position. Complete all reps on one side, then switch. Focus on controlled rotation — avoid jerking or using momentum."),
        ex("core-15", "Cable Woodchop", Category::Core, Equipment::Cable,
           &["Obliques", "Core"],
           "Set the cable to high or low position. Stand sideways to the machine, grip the handle with both hands. Pull the cable diagonally across your body in a chopping motion, rotating your torso. Return with control. Complete all reps on one side, then switch. High-to-low targets obliques differently than low-to-high."),
        ex("core-16", "Pallof Press", Category::Core, Equipment::Cable,
           &["Core", "Obliques"],
           "Set cable to chest height. Stand sideways to the machine, grip handle at your chest with both hands. Press the handle straight out in front of you, resisting the cable's pull to rotate your torso. Hold for a beat at full extension, then bring hands back to chest. This is an anti-rotation exercise — keep your hips and shoulders square throughout."),
        ex_t("core-17", "Lying Leg Raise", Category::Core, Equipment::Bodyweight,
           &["Lower Abs", "Hip Flexors"],
           "Lie flat on your back with hands at your sides or under your hips. Keeping legs straight, raise them to 90 degrees. Lower slowly back down without letting your feet touch the ground. Keep your lower back pressed into the floor throughout.",
           ExerciseTrackingType::Bodyweight),
        ex("core-18", "Farmer's Walk", Category::Core, Equipment::Dumbbell,
           &["Core", "Traps", "Forearms", "Full Body"],
           "Pick up heavy dumbbells or farmer's walk handles at your sides. Stand tall with shoulders back and core braced. Walk forward with controlled, even steps. Keep your posture upright and avoid leaning to either side. Walk for a set distance or time."),
        ex_t("core-19", "L-Sit", Category::Core, Equipment::Bodyweight,
           &["Abs", "Quads"],
           "Support yourself on parallel bars or the floor with arms straight. Lift your legs until they are parallel to the ground, forming an L shape. Hold the position with core engaged.",
           ExerciseTrackingType::Duration),
        ex_t("core-20", "Dragon Flag", Category::Core, Equipment::Bodyweight,
           &["Abs"],
           "Lie on a bench and grip the edge behind your head. Lift your entire body until only your upper back is on the bench. Lower your body as a straight plank slowly toward the bench without touching, then raise back up.",
           ExerciseTrackingType::Bodyweight),
        ex_t("core-21", "Hollow Body Hold", Category::Core, Equipment::Bodyweight,
           &["Abs"],
           "Lie on your back. Extend arms overhead and legs out straight. Lift your shoulders and legs off the ground, pressing your lower back into the floor. Hold this hollow position.",
           ExerciseTrackingType::Duration),
        ex_t("core-22", "Superman Hold", Category::Core, Equipment::Bodyweight,
           &["Glutes", "Lower Back"],
           "Lie face down with arms extended overhead. Simultaneously lift your arms, chest, and legs off the ground. Squeeze your glutes and lower back. Hold the position.",
           ExerciseTrackingType::Duration),
        ex_t("core-23", "Tuck Planche", Category::Core, Equipment::Bodyweight,
           &["Front Delts", "Chest", "Abs"],
           "Support yourself on parallel bars or the floor. Lean forward and tuck your knees to your chest while lifting your feet off the ground. Hold with arms straight and body elevated.",
           ExerciseTrackingType::Duration),

        // === CARDIO ===
        ex_t("cardio-01", "Treadmill", Category::Cardio, Equipment::Machine,
           &["Cardio", "Legs"],
           "Setup: Step onto the side rails (not the belt) and attach the safety clip to your clothing — this stops the belt if you fall. Start the machine at a low speed (2-3 km/h) and step onto the belt. Adjust speed gradually. Set incline using the incline buttons (0-15% on most machines). Controls: Speed buttons adjust pace, incline buttons adjust slope. Most machines have preset programs and a heart rate monitor on the handles. Execution: Walk, jog, or run at your target pace. Use incline to increase difficulty without increasing speed. Hold onto rails only if needed for balance. Cool down by gradually reducing speed.",
           ExerciseTrackingType::Cardio),
        ex_t("cardio-02", "Elliptical", Category::Cardio, Equipment::Machine,
           &["Cardio", "Legs", "Arms"],
           "Setup: Step onto the pedals while holding the stationary center handles for balance first. Once stable, grip the moving arm handles. Most ellipticals have resistance and incline controls on the center console. Adjust resistance to your level (start at 3-5). Execution: Stride in a smooth, oval motion — push with your legs and pull/push with your arms simultaneously. Keep your back straight and core engaged. You can reverse direction to target different muscles. The elliptical is low-impact, making it easier on joints than running. Most machines show stride rate (aim for 130-160 SPM for moderate effort).",
           ExerciseTrackingType::Cardio),
        ex_t("cardio-03", "Stationary Bike", Category::Cardio, Equipment::Machine,
           &["Cardio", "Quads", "Hamstrings"],
           "Setup: Adjust seat height so your leg has a slight bend (about 25-30 degrees) at the bottom of the pedal stroke — if your hips rock side to side, the seat is too high. For upright bikes, adjust handlebar height to a comfortable position. For recumbent bikes, adjust the seat distance so you have the same slight knee bend. Strap your feet into the pedals if clips are available. Execution: Start pedaling and adjust resistance using the console. Maintain a cadence of 60-90 RPM for steady state cardio. Keep your upper body relaxed, avoid gripping handlebars too tightly. Most bikes have preset programs for intervals, hills, etc.",
           ExerciseTrackingType::Cardio),
        ex_t("cardio-04", "Rowing Machine", Category::Cardio, Equipment::Machine,
           &["Cardio", "Back", "Legs", "Arms"],
           "Setup: Sit on the sliding seat and strap your feet into the footplates — the strap should go across the widest part of your foot (ball of foot area). Adjust the damper setting on the side of the fan (3-5 is good for most people; higher is not necessarily harder, it changes the feel). Grip the handle with an overhand grip. Execution: The stroke has 4 phases — Catch: slide forward, shins vertical, arms straight. Drive: push with legs first (60% of power), then lean back slightly, then pull handle to lower ribs. Finish: legs straight, slight lean back, handle at lower ribs. Recovery: extend arms, lean forward, bend knees, slide to catch. Keep the chain level throughout.",
           ExerciseTrackingType::Cardio),
        ex_t("cardio-05", "Stair Climber", Category::Cardio, Equipment::Machine,
           &["Cardio", "Quads", "Glutes", "Calves"],
           "Setup: Step onto the machine while holding the side rails. Most stair climbers have rotating steps or pedal-style steps. Start at a slow speed (level 3-5) to find your rhythm before increasing. Execution: Step at a steady, consistent pace. Push through your whole foot, not just your toes. Stand upright — the most common mistake is leaning heavily on the rails, which reduces the workout significantly. Use rails for balance only with a light touch. Keep your core engaged and posture tall. For more glute activation, take deeper steps. Most machines display floors climbed and step rate.",
           ExerciseTrackingType::Cardio),
        ex_t("cardio-06", "Jump Rope", Category::Cardio, Equipment::Other,
           &["Cardio", "Calves", "Shoulders"],
           "Swing rope over head, jump with both feet. Keep jumps small and consistent.",
           ExerciseTrackingType::Bodyweight),
        ex_t("cardio-07", "Battle Ropes", Category::Cardio, Equipment::Other,
           &["Cardio", "Arms", "Shoulders", "Core"],
           "Hold rope ends. Make alternating or simultaneous waves with intensity.",
           ExerciseTrackingType::Bodyweight),
        ex_t("cardio-08", "Burpees", Category::Cardio, Equipment::Bodyweight,
           &["Cardio", "Full Body"],
           "Squat, kick feet back to push-up, jump feet forward, jump up with arms overhead.",
           ExerciseTrackingType::Bodyweight),
        ex_t("cardio-09", "Air Bike", Category::Cardio, Equipment::Machine,
           &["Cardio", "Legs", "Arms"],
           "Setup: Adjust the seat height so you have a slight bend in your knee at the bottom of the pedal stroke. Grip the moving arm handles. Execution: Pedal and push/pull the handles simultaneously. The fan resistance increases the harder you push — the faster you go, the more resistance you get. Great for intervals: go all-out for 20-30 seconds, rest, repeat. Monitor calories or RPM on the display.",
           ExerciseTrackingType::Cardio),
        ex_t("cardio-10", "Ski Erg", Category::Cardio, Equipment::Machine,
           &["Cardio", "Lats", "Arms", "Core"],
           "Setup: Stand facing the machine and grip the handles with arms extended overhead. Execution: Pull both handles down simultaneously by hinging at the hips and driving your arms down past your sides. Extend back up and let your arms return overhead. The motion mimics cross-country skiing. Keep your core engaged and use your legs to help generate power. Great for full-body conditioning.",
           ExerciseTrackingType::Cardio),
        ex_t("cardio-11", "Kettlebell Swing", Category::Cardio, Equipment::Kettlebell,
           &["Glutes", "Hamstrings", "Core", "Cardio"],
           "Stand with feet shoulder-width apart, kettlebell on the floor in front of you. Hinge at the hips, grip the kettlebell with both hands. Hike it back between your legs, then drive your hips forward explosively to swing the kettlebell to chest or overhead height. Let gravity bring it back down and hinge again. Keep your arms relaxed — the power comes from your hips.",
           ExerciseTrackingType::Strength),
    ]
}
